// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.adffaces.chapter9.components;

import javax.faces.view.facelets.FaceletContext;
import javax.faces.view.facelets.ComponentConfig;
import javax.faces.view.facelets.MetaRuleset;
import org.apache.myfaces.trinidad.facelets.MethodRule;
import oracle.adfinternal.view.faces.facelets.rich.IncludeHandler;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;

public class RedButtonHandler extends IncludeHandler {

  private static final String _VIEW_ID = "/components/redButton.jsf";

  public RedButtonHandler(ComponentConfig config) {
    super(config);
  }

  protected String getViewId(FaceletContext ctx) {
    return _VIEW_ID;
  }

  protected RichDeclarativeComponent createComponent() {
    return new RedButtonComponent();
  }

  @Override
  protected MetaRuleset createMetaRuleset(Class type)
  {
    MetaRuleset m = super.createMetaRuleset(type);
    m.addRule(new MethodRule("action", java.lang.String.class, new Class[]{}));
    m.addRule(new MethodRule("actionListener", null, new Class[]{javax.faces.event.ActionEvent.class}));
    return m;
  }
}
