package com.adffaces.chapter9.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 03 05:55:52 GMT 2014
// ---------------------------------------------------------------------
public interface Chapter9AM extends ApplicationModule {
    void throwRuntimeException();
}

