package com.adffaces.chapter9.model;

import com.adffaces.chapter9.model.common.Chapter9AM;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Mar 03 05:55:00 GMT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Chapter9AMImpl extends ApplicationModuleImpl implements Chapter9AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Chapter9AMImpl() {
    }

    /**
     * Container's getter for Countries1.
     * @return Countries1
     */
    public ViewObjectImpl getCountries1() {
        return (ViewObjectImpl) findViewObject("Countries1");
    }

    public void throwRuntimeException(){
        throw new JboException("Unexcepted Error Occured");
    }
    /**
     * Container's getter for Departments1.
     * @return Departments1
     */
    public ViewObjectImpl getDepartments1() {
        return (ViewObjectImpl) findViewObject("Departments1");
    }

    /**
     * Container's getter for Employees1.
     * @return Employees1
     */
    public ViewObjectImpl getEmployees1() {
        return (ViewObjectImpl) findViewObject("Employees1");
    }

    /**
     * Container's getter for Locations1.
     * @return Locations1
     */
    public ViewObjectImpl getLocations1() {
        return (ViewObjectImpl) findViewObject("Locations1");
    }

    /**
     * Container's getter for Regions1.
     * @return Regions1
     */
    public ViewObjectImpl getRegions1() {
        return (ViewObjectImpl) findViewObject("Regions1");
    }

    /**
     * Container's getter for Tasks1.
     * @return Tasks1
     */
    public ViewObjectImpl getTasks1() {
        return (ViewObjectImpl) findViewObject("Tasks1");
    }

    /**
     * Container's getter for Departments2.
     * @return Departments2
     */
    public ViewObjectImpl getDepartments2() {
        return (ViewObjectImpl) findViewObject("Departments2");
    }

    /**
     * Container's getter for Employees2.
     * @return Employees2
     */
    public ViewObjectImpl getEmployees2() {
        return (ViewObjectImpl) findViewObject("Employees2");
    }

    /**
     * Container's getter for Employees3.
     * @return Employees3
     */
    public ViewObjectImpl getEmployees3() {
        return (ViewObjectImpl) findViewObject("Employees3");
    }

    /**
     * Container's getter for Departments3.
     * @return Departments3
     */
    public ViewObjectImpl getDepartments3() {
        return (ViewObjectImpl) findViewObject("Departments3");
    }

    /**
     * Container's getter for Locations2.
     * @return Locations2
     */
    public ViewObjectImpl getLocations2() {
        return (ViewObjectImpl) findViewObject("Locations2");
    }

    /**
     * Container's getter for Countries2.
     * @return Countries2
     */
    public ViewObjectImpl getCountries2() {
        return (ViewObjectImpl) findViewObject("Countries2");
    }

    /**
     * Container's getter for Tasks2.
     * @return Tasks2
     */
    public ViewObjectImpl getTasks2() {
        return (ViewObjectImpl) findViewObject("Tasks2");
    }

    /**
     * Container's getter for Tasks3.
     * @return Tasks3
     */
    public ViewObjectImpl getTasks3() {
        return (ViewObjectImpl) findViewObject("Tasks3");
    }

    /**
     * Container's getter for DepartmentsEmployeesFk1VL1.
     * @return DepartmentsEmployeesFk1VL1
     */
    public ViewLinkImpl getDepartmentsEmployeesFk1VL1() {
        return (ViewLinkImpl) findViewLink("DepartmentsEmployeesFk1VL1");
    }

    /**
     * Container's getter for EmployeesEmployeesFk1VL1.
     * @return EmployeesEmployeesFk1VL1
     */
    public ViewLinkImpl getEmployeesEmployeesFk1VL1() {
        return (ViewLinkImpl) findViewLink("EmployeesEmployeesFk1VL1");
    }

    /**
     * Container's getter for EmployeesDepartmentsFk1VL1.
     * @return EmployeesDepartmentsFk1VL1
     */
    public ViewLinkImpl getEmployeesDepartmentsFk1VL1() {
        return (ViewLinkImpl) findViewLink("EmployeesDepartmentsFk1VL1");
    }

    /**
     * Container's getter for DepartmentsLocationsFk1VL1.
     * @return DepartmentsLocationsFk1VL1
     */
    public ViewLinkImpl getDepartmentsLocationsFk1VL1() {
        return (ViewLinkImpl) findViewLink("DepartmentsLocationsFk1VL1");
    }

    /**
     * Container's getter for LocationsCountriesFk1VL1.
     * @return LocationsCountriesFk1VL1
     */
    public ViewLinkImpl getLocationsCountriesFk1VL1() {
        return (ViewLinkImpl) findViewLink("LocationsCountriesFk1VL1");
    }

    /**
     * Container's getter for CountriesRegionsFk1VL1.
     * @return CountriesRegionsFk1VL1
     */
    public ViewLinkImpl getCountriesRegionsFk1VL1() {
        return (ViewLinkImpl) findViewLink("CountriesRegionsFk1VL1");
    }

    /**
     * Container's getter for TasksTasksFk1VL1.
     * @return TasksTasksFk1VL1
     */
    public ViewLinkImpl getTasksTasksFk1VL1() {
        return (ViewLinkImpl) findViewLink("TasksTasksFk1VL1");
    }

    /**
     * Container's getter for TasksEmployeesFk1VL1.
     * @return TasksEmployeesFk1VL1
     */
    public ViewLinkImpl getTasksEmployeesFk1VL1() {
        return (ViewLinkImpl) findViewLink("TasksEmployeesFk1VL1");
    }
}

