// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package com.adffaces.chapter9.components;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class BlueButtonComponent extends RichDeclarativeComponent {

  public BlueButtonComponent() {
  }

  public String getText() {
    return (String) getAttributes().get("text");
  }

  public String getInlineStyle() {
    return (String) getAttributes().get("inlineStyle");
  }

  public Boolean getDisabled() {
    return (Boolean) getAttributes().get("disabled");
  }

  public MethodExpression getAction() {
    return (MethodExpression) getAttributes().get("action");
  }

  public void setAction(MethodExpression me) {
    getAttributes().put("action", me);
  }

  public MethodExpression getActionListener() {
    return (MethodExpression) getAttributes().get("actionListener");
  }

  public void setActionListener(MethodExpression me) {
    getAttributes().put("actionListener", me);
  }


  public java.lang.String handleAction() {
    RequestContext.getCurrentInstance().partialUpdateNotify(this);
    MethodExpression me = getAction();
    if (me != null) {
      return (java.lang.String) me.invoke(FacesContext.getCurrentInstance().getELContext(),
        new Object[] {});
    }
    return null;
  }

  public void handleActionListener(javax.faces.event.ActionEvent param1) {
    RequestContext.getCurrentInstance().partialUpdateNotify(this);
    MethodExpression me = getActionListener();
    if (me != null) {
      me.invoke(FacesContext.getCurrentInstance().getELContext(),
        new Object[] {param1});
    }
  }


}
